"""
Tests for engine/genome_build.py — genome build detection and gating.
"""
import pytest

from engine.genome_build import detect_build, assert_supported_build, SUPPORTED_BUILD


_VCF38 = (
    b"##fileformat=VCFv4.2\n"
    b"##reference=GRCh38\n"
    b"##contig=<ID=1,length=248956422>\n"
    b"#CHROM\tPOS\tID\tREF\tALT\n"
)
_VCF37 = (
    b"##fileformat=VCFv4.2\n"
    b"##reference=hg19\n"
    b"##contig=<ID=1,length=249250621>\n"
    b"#CHROM\tPOS\tID\tREF\tALT\n"
)
_23ANDME_B37 = (
    b"# This data file generated by 23andMe\n"
    b"# reference human assembly build 37\n"
    b"# rsid\tchromosome\tposition\tgenotype\n"
    b"rs1\t1\t69869\tTT\n"
)


def test_detects_grch38_from_contig_length():
    d = detect_build(_VCF38, "x.vcf")
    assert d["build"] == "GRCh38"
    assert d["confidence"] == "high"


def test_detects_grch37_from_contig_length():
    d = detect_build(_VCF37, "x.vcf")
    assert d["build"] == "GRCh37"


def test_detects_build37_from_23andme_header():
    d = detect_build(_23ANDME_B37, "genome.txt")
    assert d["build"] == "GRCh37"


def test_csv_is_unknown():
    d = detect_build(b"chrom,pos,ref,alt\n1,100,A,T\n", "x.csv")
    assert d["build"] == "unknown"


def test_assert_rejects_grch37_vcf():
    with pytest.raises(ValueError, match=f"only supports {SUPPORTED_BUILD}"):
        assert_supported_build(_VCF37, "x.vcf")


def test_assert_allows_grch38_vcf():
    d = assert_supported_build(_VCF38, "x.vcf")
    assert d["build"] == "GRCh38"


def test_assert_allows_build37_23andme_because_rsid_resolved():
    # 23andMe positions are discarded and rsIDs re-resolved on GRCh38, so a
    # build-37 consumer file must NOT be rejected — only recorded.
    d = assert_supported_build(_23ANDME_B37, "genome.txt")
    assert d["build"] == "GRCh37"


def test_assert_allows_unknown_csv():
    d = assert_supported_build(b"chrom,pos,ref,alt\n1,100,A,T\n", "x.csv")
    assert d["build"] == "unknown"
