"""
engine/peptides/measurements.py
================================
Structured biomarker measurement records per peptide, designed to feed a
predictive model. Each BiomarkerMeasurement carries modality, specimen,
unit, expected direction, timeframe window, and qualitative effect size.

Citations (citation_apa, doi) are deliberately left as None on each
measurement — the consumer should inherit the panel-level citation from
PEPTIDE_BIOMARKERS in biomarkers.py. Every measurement here is grounded
in the scite-verified review paper attached to its peptide's panel.

If a measurement needs its own citation distinct from the panel reference,
set citation_apa and doi explicitly on that record.
"""
from __future__ import annotations

from .biomarkers import BiomarkerMeasurement


PEPTIDE_MEASUREMENTS: dict[str, tuple[BiomarkerMeasurement, ...]] = {
    "BPC-157": (
        BiomarkerMeasurement("Serum VEGF", "proteomic", "serum", "pg/mL",
            "increase", 2.0, 8.0, "mechanism",
            effect_size="dose-dependent rise consistent with angiogenic VEGF/eNOS axis"),
        BiomarkerMeasurement("Plasma nitrite/nitrate (NOx)", "metabolomic", "plasma", "umol/L",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="rise in NO metabolites reflecting eNOS upregulation"),
        BiomarkerMeasurement("Serum IL-6", "cytokine", "serum", "pg/mL",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="reduction in pro-inflammatory cytokines tracking tendon/gut repair"),
        BiomarkerMeasurement("Serum TNF-alpha", "cytokine", "serum", "pg/mL",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="anti-inflammatory effect tied to MSK/gut benefit"),
        BiomarkerMeasurement("Pain VAS", "patient_reported", "self-report", "score (0-10)",
            "decrease", 2.0, 12.0, "efficacy",
            effect_size="clinically meaningful pain reduction in MSK case series"),
        BiomarkerMeasurement("Tendon thickness (ultrasound)", "imaging", "tendon US", "mm",
            "variable", 4.0, 12.0, "efficacy",
            effect_size="normalization of tendon architecture; thickness may transiently rise then remodel"),
        BiomarkerMeasurement("Joint range of motion", "functional", "physical exam", "degrees",
            "increase", 4.0, 12.0, "efficacy",
            effect_size="improved ROM reported across orthopaedic case series"),
        BiomarkerMeasurement("ALT", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 12.0, "safety",
            effect_size="no hepatotoxicity signal in systematic review"),
        BiomarkerMeasurement("Serum creatinine", "clinical_chem", "serum", "mg/dL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="no renal toxicity signal in available human data"),
    ),
    "TB-500": (
        BiomarkerMeasurement("Serum VEGF", "proteomic", "serum", "pg/mL",
            "increase", 1.0, 6.0, "mechanism",
            effect_size="VEGF-mediated angiogenesis in cardiac/soft tissue models"),
        BiomarkerMeasurement("MMP-2 activity", "proteomic", "serum", "ng/mL",
            "increase", 2.0, 8.0, "mechanism",
            effect_size="MMP-2/MMP-9 upregulation in tissue-remodeling studies"),
        BiomarkerMeasurement("Hepatic alpha-SMA expression", "transcriptomic", "liver biopsy", "relative expression",
            "decrease", 4.0, 12.0, "mechanism",
            effect_size="TB4 suppresses stellate-cell activation in fibrosis models"),
        BiomarkerMeasurement("Serum hyaluronic acid", "clinical_chem", "serum", "ng/mL",
            "decrease", 4.0, 24.0, "efficacy",
            effect_size="circulating fibrosis marker falls in preclinical liver-fibrosis models"),
        BiomarkerMeasurement("Wound closure area", "imaging", "wound photography", "% closure",
            "increase", 1.0, 6.0, "efficacy",
            effect_size="accelerated re-epithelialization in soft-tissue repair"),
        BiomarkerMeasurement("Hair density (trichoscopy)", "imaging", "scalp dermoscopy", "hairs/cm^2",
            "increase", 8.0, 24.0, "efficacy",
            effect_size="follicular stem-cell migration drives hair regrowth"),
        BiomarkerMeasurement("ALT", "clinical_chem", "serum", "U/L",
            "decrease", 4.0, 24.0, "efficacy",
            effect_size="transaminase improvement in fibrosis adjunct setting"),
        BiomarkerMeasurement("CBC with differential", "hematology", "whole blood", "cells/uL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="no hematologic toxicity in available human safety data"),
    ),
    "Thymosin Beta-4": (
        BiomarkerMeasurement("Corneal fluorescein staining", "imaging", "cornea", "score",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="improved corneal epithelial integrity in dry-eye studies"),
        BiomarkerMeasurement("Tear break-up time", "functional", "tear film", "seconds",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="improved tear-film stability with topical TB4"),
        BiomarkerMeasurement("Dermal wound closure", "imaging", "wound photography", "% closure",
            "increase", 1.0, 4.0, "efficacy",
            effect_size="accelerated re-epithelialization vs vehicle"),
        BiomarkerMeasurement("Hair follicle anagen induction", "imaging", "scalp dermoscopy", "% follicles in anagen",
            "increase", 4.0, 12.0, "efficacy",
            effect_size="TB4 accelerates anagen entry in mouse model"),
        BiomarkerMeasurement("Skin VEGF expression", "transcriptomic", "skin biopsy", "relative expression",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="VEGF transcript upregulation in TB4-treated skin"),
        BiomarkerMeasurement("Laminin-5 at wound edge", "proteomic", "skin biopsy", "relative expression",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="laminin-5 deposition promotes keratinocyte migration"),
        BiomarkerMeasurement("OSDI ocular symptom score", "patient_reported", "self-report", "score",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="symptomatic dry-eye improvement"),
        BiomarkerMeasurement("ALT", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 12.0, "safety",
            effect_size="no hepatic toxicity with topical or systemic TB4"),
    ),
    "GHK-Cu": (
        BiomarkerMeasurement("Dermal collagen I expression", "transcriptomic", "skin biopsy", "relative expression",
            "increase", 2.0, 12.0, "mechanism",
            effect_size="GHK-Cu upregulates type I collagen in dermal fibroblasts"),
        BiomarkerMeasurement("Dermal elastin expression", "transcriptomic", "skin biopsy", "relative expression",
            "increase", 4.0, 12.0, "mechanism",
            effect_size="elastin and decorin upregulation in treated dermis"),
        BiomarkerMeasurement("MMP-1 activity", "proteomic", "skin biopsy", "ng/mg protein",
            "biphasic", 2.0, 12.0, "mechanism",
            effect_size="early rise during remodeling, later normalization"),
        BiomarkerMeasurement("TGF-beta1 expression", "proteomic", "skin biopsy", "pg/mg protein",
            "increase", 2.0, 8.0, "mechanism",
            effect_size="TGF-beta1 induction drives ECM remodeling"),
        BiomarkerMeasurement("Wrinkle depth (imaging)", "imaging", "facial photography", "score",
            "decrease", 4.0, 12.0, "efficacy",
            effect_size="visible reduction in wrinkle depth and roughness"),
        BiomarkerMeasurement("Skin thickness (ultrasound)", "imaging", "skin US", "mm",
            "increase", 4.0, 12.0, "efficacy",
            effect_size="dermal thickness rises with ECM accumulation"),
        BiomarkerMeasurement("Hair density (trichoscopy)", "imaging", "scalp dermoscopy", "hairs/cm^2",
            "increase", 8.0, 24.0, "efficacy",
            effect_size="follicular density improvement in scalp peptide studies"),
        BiomarkerMeasurement("Serum copper", "clinical_chem", "serum", "ug/dL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="topical delivery does not appreciably elevate systemic copper"),
        BiomarkerMeasurement("Ceruloplasmin", "clinical_chem", "serum", "mg/dL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="copper-carrier protein remains within reference range"),
    ),
    "MOTS-c": (
        BiomarkerMeasurement("HOMA-IR", "clinical_chem", "serum", "index",
            "decrease", 4.0, 12.0, "efficacy",
            effect_size="improved insulin sensitivity index"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "decrease", 2.0, 12.0, "efficacy",
            effect_size="reduction in fasting glucose in IR models"),
        BiomarkerMeasurement("HbA1c", "clinical_chem", "whole blood", "%",
            "decrease", 8.0, 24.0, "efficacy",
            effect_size="downstream glycemic improvement on RBC-turnover timescale"),
        BiomarkerMeasurement("Skeletal muscle p-AMPK", "proteomic", "muscle biopsy", "p-AMPK/AMPK ratio",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="MOTS-c activates AMPK to enhance glucose uptake"),
        BiomarkerMeasurement("Plasma folate-cycle metabolites", "metabolomic", "plasma", "umol/L",
            "variable", 2.0, 8.0, "mechanism",
            effect_size="MOTS-c modulates folate-methionine flux influencing AMPK"),
        BiomarkerMeasurement("VO2max", "functional", "CPET", "mL/kg/min",
            "increase", 4.0, 12.0, "efficacy",
            effect_size="improved exercise capacity in aged/IR models"),
        BiomarkerMeasurement("Serum IL-6", "cytokine", "serum", "pg/mL",
            "decrease", 4.0, 12.0, "efficacy",
            effect_size="reduced inflammatory tone with metabolic improvement"),
        BiomarkerMeasurement("ALT", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 12.0, "safety",
            effect_size="no hepatic safety signal in published data"),
        BiomarkerMeasurement("Serum lactate", "clinical_chem", "serum", "mmol/L",
            "no_change", 2.0, 12.0, "safety",
            effect_size="mitochondrial-derived peptide does not provoke lactic acidosis"),
    ),
    "CJC-1295": (
        BiomarkerMeasurement("Serum IGF-1", "hormone", "serum", "ng/mL",
            "increase", 1.0, 8.0, "efficacy",
            effect_size="sustained rise above baseline with weekly dosing"),
        BiomarkerMeasurement("Serum IGFBP-3", "hormone", "serum", "mg/L",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="parallel rise with IGF-1"),
        BiomarkerMeasurement("GH peak", "hormone", "serum", "ng/mL",
            "increase", 0.0, 0.5, "mechanism",
            effect_size="amplified pulsatile GH release"),
        BiomarkerMeasurement("Lean body mass (DXA)", "imaging", "whole-body DXA", "kg",
            "increase", 8.0, 24.0, "efficacy",
            effect_size="modest gain over months"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "variable", 4.0, 12.0, "safety",
            effect_size="possible mild rise from GH-mediated insulin resistance"),
        BiomarkerMeasurement("HbA1c", "clinical_chem", "whole blood", "%",
            "variable", 12.0, 24.0, "safety",
            effect_size="monitor for upward drift"),
        BiomarkerMeasurement("PSA", "clinical_chem", "serum", "ng/mL",
            "no_change", 12.0, 24.0, "safety",
            effect_size="monitor in men >40 given IGF-1 elevation"),
        BiomarkerMeasurement("Edema / carpal tunnel exam", "physical", "clinical exam", "present/absent",
            "variable", 2.0, 12.0, "safety",
            effect_size="classic GH-excess side effect"),
        BiomarkerMeasurement("IGF-1 vs age-adjusted reference", "hormone", "serum", "z-score",
            "no_change", 4.0, 24.0, "safety",
            effect_size="should remain within age-adjusted upper limit"),
    ),
    "Ipamorelin": (
        BiomarkerMeasurement("Serum IGF-1", "hormone", "serum", "ng/mL",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="rise above baseline with chronic dosing"),
        BiomarkerMeasurement("Serum IGFBP-3", "hormone", "serum", "mg/L",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="parallel rise with IGF-1"),
        BiomarkerMeasurement("GH AUC", "hormone", "serum", "ng*h/mL",
            "increase", 0.0, 0.1, "mechanism",
            effect_size="ghrelin-receptor-mediated pulsatile GH release"),
        BiomarkerMeasurement("Serum cortisol", "hormone", "serum", "ug/dL",
            "no_change", 0.0, 0.5, "selectivity",
            effect_size="lack of cortisol rise defines ipamorelin selectivity"),
        BiomarkerMeasurement("Serum prolactin", "hormone", "serum", "ng/mL",
            "no_change", 0.0, 0.5, "selectivity",
            effect_size="lack of prolactin rise defines ipamorelin selectivity"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "variable", 4.0, 12.0, "safety",
            effect_size="monitor for GH-mediated insulin resistance"),
        BiomarkerMeasurement("Lean body mass (DXA)", "imaging", "whole-body DXA", "kg",
            "increase", 12.0, 24.0, "efficacy",
            effect_size="modest gain in sarcopenia adjunct use"),
    ),
    "GHRP-2": (
        BiomarkerMeasurement("GH peak", "hormone", "serum", "ng/mL",
            "increase", 0.0, 0.1, "efficacy",
            effect_size="robust GH peak used as diagnostic stim"),
        BiomarkerMeasurement("Serum IGF-1", "hormone", "serum", "ng/mL",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="rise with repeated dosing"),
        BiomarkerMeasurement("Serum IGFBP-3", "hormone", "serum", "mg/L",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="parallel rise with IGF-1"),
        BiomarkerMeasurement("Body weight", "physical", "patient", "kg",
            "increase", 4.0, 12.0, "efficacy",
            effect_size="appetite-driven weight gain in cachexia"),
        BiomarkerMeasurement("Serum cortisol", "hormone", "serum", "ug/dL",
            "increase", 0.0, 0.1, "safety",
            effect_size="modest rise (less selective than ipamorelin)"),
        BiomarkerMeasurement("Serum prolactin", "hormone", "serum", "ng/mL",
            "increase", 0.0, 0.1, "safety",
            effect_size="modest rise reported with GHRP class"),
        BiomarkerMeasurement("Serum ACTH", "hormone", "plasma", "pg/mL",
            "increase", 0.0, 0.1, "safety",
            effect_size="acute rise reflects HPA activation"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "variable", 4.0, 12.0, "safety",
            effect_size="monitor for GH-mediated insulin resistance"),
    ),
    "MGF": (
        BiomarkerMeasurement("Lean body mass (DXA)", "imaging", "whole-body DXA", "kg",
            "increase", 8.0, 24.0, "efficacy",
            effect_size="muscle mass gain with repair stimulus"),
        BiomarkerMeasurement("Satellite cell markers (Pax7/MyoD)", "transcriptomic", "muscle biopsy", "relative expression",
            "increase", 0.5, 4.0, "mechanism",
            effect_size="enhanced myogenic precursor activation"),
        BiomarkerMeasurement("Serum IGF-1", "hormone", "serum", "ng/mL",
            "variable", 2.0, 12.0, "mechanism",
            effect_size="local muscle IGF-1Ec splice variant; systemic IGF-1 modestly tracked"),
        BiomarkerMeasurement("Grip strength", "functional", "dynamometer", "kg",
            "increase", 8.0, 24.0, "efficacy",
            effect_size="improvement in sarcopenia adjunct use"),
        BiomarkerMeasurement("Myogenic precursor engraftment", "proteomic", "muscle biopsy", "cells/field",
            "increase", 1.0, 8.0, "mechanism",
            effect_size="enhanced transplant success in preclinical model"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="monitor given IGF-axis activity"),
        BiomarkerMeasurement("IGF-1 vs age-adjusted reference", "hormone", "serum", "z-score",
            "no_change", 4.0, 24.0, "safety",
            effect_size="should remain within age-adjusted upper limit"),
    ),
    "AOD-9604": (
        BiomarkerMeasurement("Body weight", "physical", "patient", "kg",
            "decrease", 4.0, 24.0, "efficacy",
            effect_size="modest reduction in trials"),
        BiomarkerMeasurement("Waist circumference", "physical", "tape measure", "cm",
            "decrease", 8.0, 24.0, "efficacy",
            effect_size="reduction tracking adiposity loss"),
        BiomarkerMeasurement("% body fat (DXA)", "imaging", "whole-body DXA", "%",
            "decrease", 8.0, 24.0, "efficacy",
            effect_size="reduction in fat mass fraction"),
        BiomarkerMeasurement("Serum leptin", "hormone", "serum", "ng/mL",
            "decrease", 4.0, 24.0, "mechanism",
            effect_size="falls in proportion to fat mass loss"),
        BiomarkerMeasurement("WADA hGH isoform immunoassay", "proteomic", "serum", "ratio",
            "no_change", 0.0, 0.5, "selectivity",
            effect_size="no interference confirms AOD-9604 is not hGH"),
        BiomarkerMeasurement("Lipid panel", "lipidomic", "serum", "mg/dL",
            "variable", 8.0, 24.0, "safety",
            effect_size="track alongside adiposity reduction"),
        BiomarkerMeasurement("Fasting glucose", "clinical_chem", "serum", "mg/dL",
            "no_change", 4.0, 12.0, "safety",
            effect_size="AOD-9604 lacks GH-like glycemic effect"),
    ),
    "Thymosin Alpha-1": (
        BiomarkerMeasurement("CD4/CD8 ratio", "hematology", "peripheral blood", "ratio",
            "increase", 2.0, 12.0, "efficacy",
            effect_size="restoration toward 1.5-2.0 in immunocompromised/sepsis patients"),
        BiomarkerMeasurement("Absolute CD4+ T-lymphocyte count", "hematology", "peripheral blood", "cells/uL",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="reversal of CD4 lymphopenia in sepsis / chronic viral infection"),
        BiomarkerMeasurement("HBV DNA / HCV RNA viral load", "clinical_chem", "serum", "IU/mL (log10)",
            "decrease", 12.0, 48.0, "efficacy",
            effect_size="sustained virologic response as adjunct in chronic HBV/HCV"),
        BiomarkerMeasurement("Stimulated PBMC IFN-gamma", "cytokine", "PBMC stimulation assay", "pg/mL",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="Th1 polarization; restored IFN-gamma in sepsis/CHB"),
        BiomarkerMeasurement("TLR9 / MyD88 pathway expression", "transcriptomic", "peripheral blood DCs", "relative mRNA",
            "increase", 0.5, 2.0, "mechanism",
            effect_size="TLR9 signaling upregulation drives pDC/mDC activation"),
        BiomarkerMeasurement("Serum IL-6", "cytokine", "serum", "pg/mL",
            "decrease", 1.0, 4.0, "mechanism",
            effect_size="attenuation of hyperinflammatory cytokine release in severe COVID/sepsis"),
        BiomarkerMeasurement("Monocyte HLA-DR (mHLA-DR)", "proteomic", "PB monocytes (flow cytometry)", "MFI",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="reversal of sepsis-induced monocyte deactivation"),
        BiomarkerMeasurement("Liver function tests (ALT, AST)", "clinical_chem", "serum", "U/L",
            "variable", 4.0, 24.0, "safety",
            effect_size="monitor hepatic safety during chronic viral hepatitis adjunct"),
    ),
    "Epitalon": (
        BiomarkerMeasurement("Nocturnal serum melatonin", "hormone", "serum (nocturnal sampling)", "pg/mL",
            "increase", 2.0, 12.0, "efficacy",
            effect_size="restoration of age-related decline in nocturnal melatonin amplitude"),
        BiomarkerMeasurement("Urinary 6-sulfatoxymelatonin (aMT6s)", "metabolomic", "overnight urine", "ng/night",
            "increase", 2.0, 12.0, "efficacy",
            effect_size="surrogate of total nocturnal melatonin output"),
        BiomarkerMeasurement("Pineal AANAT expression", "transcriptomic", "pineal tissue / plasma exosomal mRNA", "relative expression",
            "increase", 2.0, 8.0, "mechanism",
            effect_size="upregulation of arylalkylamine N-acetyltransferase drives melatonin synthesis"),
        BiomarkerMeasurement("Telomerase activity in PBMCs", "proteomic", "PBMCs", "TRAP units",
            "increase", 4.0, 24.0, "mechanism",
            effect_size="induction of telomerase activity as anti-senescence mechanism"),
        BiomarkerMeasurement("Leukocyte telomere length (qPCR T/S)", "transcriptomic", "PB leukocytes", "T/S ratio",
            "increase", 24.0, 104.0, "efficacy",
            effect_size="attenuation of age-related telomere shortening over long-term dosing"),
        BiomarkerMeasurement("Pittsburgh Sleep Quality Index (PSQI)", "patient_reported", "self-report", "PSQI score",
            "decrease", 4.0, 12.0, "efficacy",
            effect_size="improvement in subjective sleep quality with circadian restoration"),
        BiomarkerMeasurement("Serum hs-CRP", "clinical_chem", "serum", "mg/L",
            "decrease", 4.0, 24.0, "mechanism",
            effect_size="reduction of inflammaging marker"),
        BiomarkerMeasurement("Cancer surveillance panel", "clinical_chem", "serum + age-appropriate imaging", "composite",
            "no_change", 12.0, 104.0, "safety",
            effect_size="monitor for theoretical neoplasia risk from telomerase induction"),
    ),
    "Selank": (
        BiomarkerMeasurement("Hamilton Anxiety (HAM-A)", "patient_reported", "clinician-administered", "HAM-A score",
            "decrease", 2.0, 4.0, "efficacy",
            effect_size="anxiolytic effect comparable to benzodiazepines in GAD, without sedation"),
        BiomarkerMeasurement("GAD-7 score", "patient_reported", "self-report", "GAD-7 score",
            "decrease", 2.0, 4.0, "efficacy",
            effect_size="reduction in generalized anxiety severity"),
        BiomarkerMeasurement("Plasma BDNF", "proteomic", "plasma", "ng/mL",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="upregulation of BDNF in limbic regions; plasma surrogate"),
        BiomarkerMeasurement("GABA-A / enkephalinase pathway expression", "transcriptomic", "hippocampal tissue / peripheral surrogate", "relative mRNA",
            "increase", 0.0, 2.0, "mechanism",
            effect_size="modulation of GABAergic tone and enkephalin metabolism underlies anxiolysis"),
        BiomarkerMeasurement("Salivary cortisol (diurnal AUC)", "hormone", "saliva (4-point)", "nmol/L*h",
            "decrease", 2.0, 6.0, "mechanism",
            effect_size="HPA-axis normalization in anxiety-asthenia syndrome"),
        BiomarkerMeasurement("Urinary cortisol metabolites (THE)", "metabolomic", "24h urine", "ug/24h",
            "decrease", 2.0, 6.0, "mechanism",
            effect_size="integrative readout of total glucocorticoid output"),
        BiomarkerMeasurement("Stroop / CPT attention test", "functional", "neurocognitive testing", "ms / %",
            "increase", 0.0, 2.0, "efficacy",
            effect_size="improved attention and processing speed in asthenic patients"),
        BiomarkerMeasurement("CBC + BMP (safety panel)", "hematology", "PB / serum", "composite",
            "no_change", 2.0, 12.0, "safety",
            effect_size="routine tolerability monitoring; minimal off-target toxicity"),
    ),
    "Semax": (
        BiomarkerMeasurement("NIHSS", "functional", "neurological exam", "NIHSS points",
            "decrease", 1.0, 12.0, "efficacy",
            effect_size="accelerated improvement when given in acute ischemic stroke window"),
        BiomarkerMeasurement("MoCA", "functional", "cognitive exam", "MoCA points",
            "increase", 4.0, 24.0, "efficacy",
            effect_size="improvement in post-stroke / vascular cognitive impairment"),
        BiomarkerMeasurement("Serum BDNF", "proteomic", "serum", "ng/mL",
            "increase", 0.0, 4.0, "mechanism",
            effect_size="BDNF expression drives neuroplasticity and recovery"),
        BiomarkerMeasurement("Serum NGF", "proteomic", "serum", "pg/mL",
            "increase", 0.0, 4.0, "mechanism",
            effect_size="NGF induction; trophic support for cholinergic neurons"),
        BiomarkerMeasurement("Neurotrophin transcript expression", "transcriptomic", "PB leukocytes (surrogate)", "relative mRNA",
            "increase", 0.0, 2.0, "mechanism",
            effect_size="neurotrophic gene programs upregulated after acute administration"),
        BiomarkerMeasurement("Serum S100B", "proteomic", "serum", "ug/L",
            "decrease", 0.0, 2.0, "mechanism",
            effect_size="reduced neuronal/glial damage marker after ischemic insult"),
        BiomarkerMeasurement("DWI MRI infarct volume", "imaging", "brain MRI (DWI)", "cm^3",
            "decrease", 0.0, 4.0, "efficacy",
            effect_size="smaller final infarct when initiated in therapeutic window"),
        BiomarkerMeasurement("Blood pressure / heart rate", "physical", "vital signs", "mmHg / bpm",
            "no_change", 0.0, 12.0, "safety",
            effect_size="hemodynamic neutrality at therapeutic doses"),
    ),
    "DSIP": (
        BiomarkerMeasurement("Polysomnography slow-wave sleep %", "functional", "overnight PSG", "% TST",
            "increase", 0.0, 2.0, "efficacy",
            effect_size="increased N3/delta sleep proportion in chronic insomnia"),
        BiomarkerMeasurement("Sleep onset latency", "functional", "PSG / actigraphy", "minutes",
            "decrease", 0.0, 4.0, "efficacy",
            effect_size="shorter time to persistent sleep in insomnia"),
        BiomarkerMeasurement("Pittsburgh Sleep Quality Index (PSQI)", "patient_reported", "self-report", "PSQI score",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="subjective sleep quality improvement"),
        BiomarkerMeasurement("COWS opiate withdrawal score", "patient_reported", "clinician-administered", "COWS score",
            "decrease", 0.0, 2.0, "efficacy",
            effect_size="attenuation of opioid withdrawal symptom severity"),
        BiomarkerMeasurement("CSF / serum 5-HIAA", "metabolomic", "CSF or serum", "nmol/L",
            "variable", 0.0, 4.0, "mechanism",
            effect_size="modulation of serotonergic turnover (5-HT to 5-HIAA pathway)"),
        BiomarkerMeasurement("Tryptophan hydroxylase / 5-HT pathway expression", "transcriptomic", "brainstem raphe / peripheral surrogate", "relative mRNA",
            "increase", 0.0, 2.0, "mechanism",
            effect_size="serotonergic pathway modulation implicated in sleep induction"),
        BiomarkerMeasurement("Brief Pain Inventory severity", "patient_reported", "self-report", "BPI score (0-10)",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="chronic pain severity reduction reported clinically"),
        BiomarkerMeasurement("Morning plasma cortisol", "hormone", "plasma (AM)", "ug/dL",
            "decrease", 1.0, 4.0, "mechanism",
            effect_size="normalization of HPA hyperactivity in stress/withdrawal"),
    ),
    "Dihexa": (
        BiomarkerMeasurement("MoCA score", "patient_reported", "self-report", "score",
            "increase", 4.0, 24.0, "efficacy",
            effect_size="improvement in global cognitive function"),
        BiomarkerMeasurement("ADAS-Cog 13", "patient_reported", "clinician-administered", "score",
            "decrease", 12.0, 52.0, "efficacy",
            effect_size="reduction reflecting cognitive improvement"),
        BiomarkerMeasurement("Motor performance (rotarod/UPDRS-III)", "functional", "behavioral assay", "latency seconds / score",
            "increase", 2.0, 12.0, "efficacy",
            effect_size="restored motor coordination in 3-NP model"),
        BiomarkerMeasurement("Serum HGF", "proteomic", "serum", "pg/mL",
            "increase", 1.0, 12.0, "mechanism",
            effect_size="HGF/c-Met pathway activation downstream of Dihexa"),
        BiomarkerMeasurement("Hippocampal c-Met phosphorylation", "proteomic", "brain tissue (preclinical)", "phospho/total ratio",
            "increase", 0.5, 8.0, "mechanism",
            effect_size="activation of HGF receptor signaling"),
        BiomarkerMeasurement("Striatal volume (MRI)", "imaging", "brain MRI", "mm^3",
            "increase", 12.0, 52.0, "efficacy",
            effect_size="attenuation of neurodegenerative atrophy"),
        BiomarkerMeasurement("Plasma kynurenine/tryptophan", "metabolomic", "plasma", "ratio",
            "decrease", 4.0, 24.0, "mechanism",
            effect_size="reduced neuroinflammatory IDO activity"),
        BiomarkerMeasurement("Oncologic surveillance panel", "clinical_chem", "serum + imaging", "composite",
            "no_change", 12.0, 52.0, "safety",
            effect_size="monitor for HGF/c-Met-driven proliferative risk"),
    ),
    "Kisspeptin": (
        BiomarkerMeasurement("Serum LH", "hormone", "serum", "IU/L",
            "increase", 0.0, 0.5, "efficacy",
            effect_size="acute LH surge following kisspeptin administration"),
        BiomarkerMeasurement("Serum FSH", "hormone", "serum", "IU/L",
            "increase", 0.0, 2.0, "efficacy",
            effect_size="gonadotropin stimulation via GnRH release"),
        BiomarkerMeasurement("Serum estradiol", "hormone", "serum", "pg/mL",
            "increase", 1.0, 4.0, "efficacy",
            effect_size="restoration of ovarian steroidogenesis"),
        BiomarkerMeasurement("Serum testosterone (male hypogonadism)", "hormone", "serum", "ng/dL",
            "increase", 1.0, 8.0, "efficacy",
            effect_size="HPG-axis reactivation in hypogonadotropic men"),
        BiomarkerMeasurement("LH pulse frequency (GnRH pulsatility)", "hormone", "serial serum", "pulses per 8h",
            "increase", 0.0, 1.0, "mechanism",
            effect_size="restored pulsatile GnRH-driven LH secretion"),
        BiomarkerMeasurement("Dominant follicle diameter (TV-US)", "imaging", "transvaginal ultrasound", "mm",
            "increase", 1.0, 3.0, "efficacy",
            effect_size="follicular maturation and ovulation induction"),
        BiomarkerMeasurement("Mid-luteal progesterone (ovulation)", "hormone", "serum", "ng/mL",
            "increase", 2.0, 12.0, "efficacy",
            effect_size="restoration of ovulatory cycles in HA/infertility"),
        BiomarkerMeasurement("OHSS incidence", "clinical_chem", "clinical assessment", "incidence",
            "decrease", 1.0, 4.0, "safety",
            effect_size="lower OHSS risk vs hCG trigger in IVF"),
    ),
    "Melanotan II": (
        BiomarkerMeasurement("Skin melanin index", "physical", "skin (reflectance spectrophotometry)", "melanin index",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="dose-dependent increase in cutaneous pigmentation"),
        BiomarkerMeasurement("IIEF-5", "patient_reported", "self-report", "score",
            "increase", 1.0, 8.0, "efficacy",
            effect_size="improved erectile function in ED subjects"),
        BiomarkerMeasurement("Tyrosinase activity", "proteomic", "skin biopsy", "relative activity",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="MC1R-mediated upregulation of eumelanin synthesis"),
        BiomarkerMeasurement("Dermoscopic naevus surveillance", "imaging", "dermoscopy", "count and atypia score",
            "no_change", 12.0, 104.0, "safety",
            effect_size="monitor for darkening naevi and melanoma risk"),
        BiomarkerMeasurement("Blood pressure", "physical", "vital signs", "mmHg",
            "variable", 0.0, 8.0, "safety",
            effect_size="transient pressor effects reported with MC analogues"),
        BiomarkerMeasurement("Nausea / GI AE incidence", "patient_reported", "adverse-event log", "incidence",
            "increase", 0.0, 2.0, "safety",
            effect_size="commonly reported acute MC-receptor side effect"),
        BiomarkerMeasurement("LFTs (ALT/AST)", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 24.0, "safety",
            effect_size="surveillance for hepatotoxicity in unregulated use"),
    ),
    "LL-37": (
        BiomarkerMeasurement("Wound area closure", "physical", "wound photography/planimetry", "% area reduction",
            "increase", 2.0, 8.0, "efficacy",
            effect_size="accelerated closure of hard-to-heal venous leg ulcers"),
        BiomarkerMeasurement("Wound area (absolute)", "imaging", "digital wound imaging", "mm^2",
            "decrease", 2.0, 8.0, "efficacy",
            effect_size="dose-dependent reduction in ulcer area"),
        BiomarkerMeasurement("Wound bacterial bioburden", "microbiome", "wound swab/biopsy", "log10 CFU/g",
            "decrease", 1.0, 4.0, "mechanism",
            effect_size="antimicrobial activity against wound flora"),
        BiomarkerMeasurement("Wound exudate IL-8", "cytokine", "wound exudate", "pg/mL",
            "decrease", 1.0, 4.0, "mechanism",
            effect_size="modulation of pro-inflammatory chemokine milieu"),
        BiomarkerMeasurement("Serum 25-OH vitamin D", "metabolomic", "serum", "ng/mL",
            "increase", 4.0, 12.0, "mechanism",
            effect_size="vitamin D status drives endogenous CAMP/LL-37 expression"),
        BiomarkerMeasurement("CAMP cathelicidin gene expression", "transcriptomic", "wound biopsy", "relative mRNA",
            "increase", 1.0, 4.0, "mechanism",
            effect_size="cathelicidin pathway engagement at wound site"),
        BiomarkerMeasurement("Wound pain (VAS)", "patient_reported", "self-report", "VAS 0-10",
            "decrease", 1.0, 8.0, "efficacy",
            effect_size="reduced ulcer pain alongside healing"),
        BiomarkerMeasurement("Local tolerability (erythema/irritation)", "physical", "peri-wound skin", "grade",
            "no_change", 0.0, 8.0, "safety",
            effect_size="topical LL-37 well tolerated at studied doses"),
    ),
    "KPV": (
        BiomarkerMeasurement("Histologic colitis score", "imaging", "colonic biopsy histopathology", "score",
            "decrease", 1.0, 4.0, "efficacy",
            effect_size="reduced mucosal inflammation in DSS/TNBS colitis"),
        BiomarkerMeasurement("Fecal calprotectin", "proteomic", "stool", "ug/g",
            "decrease", 2.0, 12.0, "efficacy",
            effect_size="reduced neutrophilic mucosal inflammation"),
        BiomarkerMeasurement("Colonic MPO activity", "proteomic", "colonic tissue", "U/mg protein",
            "decrease", 1.0, 4.0, "mechanism",
            effect_size="decreased neutrophil infiltration"),
        BiomarkerMeasurement("NF-kB p65 nuclear translocation", "transcriptomic", "colonic epithelial cells", "relative nuclear intensity",
            "decrease", 0.0, 2.0, "mechanism",
            effect_size="KPV suppresses NF-kB signaling via PepT1 uptake"),
        BiomarkerMeasurement("Colonic IL-6 / IL-8 mRNA", "transcriptomic", "colonic biopsy", "relative mRNA",
            "decrease", 0.5, 4.0, "mechanism",
            effect_size="downregulation of pro-inflammatory cytokine transcription"),
        BiomarkerMeasurement("Body weight (colitis recovery)", "physical", "body weight", "% baseline",
            "increase", 1.0, 4.0, "efficacy",
            effect_size="attenuated weight loss in experimental colitis"),
        BiomarkerMeasurement("SCORAD index", "patient_reported", "clinician assessment", "score",
            "decrease", 4.0, 12.0, "efficacy",
            effect_size="reduced eczema severity via melanocortin anti-inflammatory action"),
        BiomarkerMeasurement("CBC + CMP safety panel", "clinical_chem", "serum", "composite",
            "no_change", 4.0, 24.0, "safety",
            effect_size="favorable systemic safety of orally absorbed tripeptide"),
    ),
    "Semaglutide": (
        BiomarkerMeasurement("Body weight", "physical", "body weight", "% baseline",
            "decrease", 4.0, 68.0, "efficacy",
            effect_size="~14.9% mean weight reduction vs ~2.4% placebo at 68 weeks (STEP 1)"),
        BiomarkerMeasurement("Waist circumference", "physical", "waist", "cm",
            "decrease", 8.0, 68.0, "efficacy",
            effect_size="sustained reduction tracking visceral adiposity loss"),
        BiomarkerMeasurement("HbA1c", "clinical_chem", "whole blood", "%",
            "decrease", 8.0, 28.0, "efficacy",
            effect_size="incretin-mediated glycemic improvement; magnitude modified by TCF7L2/GLP1R genotype"),
        BiomarkerMeasurement("Fasting plasma glucose", "clinical_chem", "plasma", "mg/dL",
            "decrease", 2.0, 12.0, "mechanism",
            effect_size="glucose-dependent insulinotropic effect"),
        BiomarkerMeasurement("HOMA-IR", "clinical_chem", "serum", "index",
            "decrease", 8.0, 28.0, "efficacy",
            effect_size="improved insulin sensitivity with weight loss"),
        BiomarkerMeasurement("Serum lipase", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 24.0, "safety",
            effect_size="monitor for pancreatitis; asymptomatic elevations possible"),
        BiomarkerMeasurement("Resting heart rate", "physical", "physical exam", "bpm",
            "increase", 2.0, 12.0, "safety",
            effect_size="small mean rise observed with GLP-1 receptor agonism"),
    ),
    "Tirzepatide": (
        BiomarkerMeasurement("Body weight", "physical", "body weight", "% baseline",
            "decrease", 4.0, 72.0, "efficacy",
            effect_size="up to ~20.9% mean weight reduction at 72 weeks (SURMOUNT-1, 15 mg)"),
        BiomarkerMeasurement("Waist circumference", "physical", "waist", "cm",
            "decrease", 8.0, 72.0, "efficacy",
            effect_size="dose-dependent reduction in central adiposity"),
        BiomarkerMeasurement("HbA1c", "clinical_chem", "whole blood", "%",
            "decrease", 8.0, 40.0, "efficacy",
            effect_size="dual GIP/GLP-1 agonism; response modified by GIPR/GLP1R/TCF7L2 genotype"),
        BiomarkerMeasurement("Fasting plasma glucose", "clinical_chem", "plasma", "mg/dL",
            "decrease", 2.0, 12.0, "mechanism",
            effect_size="glucose-dependent insulinotropic effect via dual incretin receptors"),
        BiomarkerMeasurement("HOMA-IR", "clinical_chem", "serum", "index",
            "decrease", 8.0, 40.0, "efficacy",
            effect_size="improved insulin sensitivity exceeding GLP-1 monotherapy in trials"),
        BiomarkerMeasurement("Serum lipase", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 24.0, "safety",
            effect_size="monitor for pancreatitis; asymptomatic elevations possible"),
        BiomarkerMeasurement("Resting heart rate", "physical", "physical exam", "bpm",
            "increase", 2.0, 12.0, "safety",
            effect_size="small mean rise observed with incretin receptor agonism"),
    ),
    "Liraglutide": (
        BiomarkerMeasurement("Body weight", "physical", "body weight", "% baseline",
            "decrease", 4.0, 56.0, "efficacy",
            effect_size="~8.0% mean weight reduction vs ~2.6% placebo at 56 weeks (SCALE)"),
        BiomarkerMeasurement("Waist circumference", "physical", "waist", "cm",
            "decrease", 8.0, 56.0, "efficacy",
            effect_size="reduction tracking adiposity loss"),
        BiomarkerMeasurement("HbA1c", "clinical_chem", "whole blood", "%",
            "decrease", 8.0, 26.0, "efficacy",
            effect_size="incretin-mediated glycemic improvement; modified by TCF7L2/GLP1R genotype"),
        BiomarkerMeasurement("Fasting plasma glucose", "clinical_chem", "plasma", "mg/dL",
            "decrease", 2.0, 12.0, "mechanism",
            effect_size="glucose-dependent insulinotropic effect"),
        BiomarkerMeasurement("HOMA-IR", "clinical_chem", "serum", "index",
            "decrease", 8.0, 26.0, "efficacy",
            effect_size="improved insulin sensitivity with weight loss"),
        BiomarkerMeasurement("Serum lipase", "clinical_chem", "serum", "U/L",
            "no_change", 4.0, 24.0, "safety",
            effect_size="monitor for pancreatitis; asymptomatic elevations possible"),
        BiomarkerMeasurement("Resting heart rate", "physical", "physical exam", "bpm",
            "increase", 2.0, 12.0, "safety",
            effect_size="small mean rise observed with GLP-1 receptor agonism"),
    ),
}
