"""
validation/tier_a/build_handling.py
===================================
Tier A — genome-build detection & gating validation.

This track validates `engine.genome_build` — the control that mitigates the
master plan's #1 launch-blocking hazard, **H-01 (silent GRCh37/GRCh38
conflation)**. Every coordinate-based annotator assumes GRCh38; if a GRCh37 VCF
is processed as GRCh38, every annotation is silently wrong. The detector must
(a) identify the build and (b) **gate** coordinate files correctly: proceed only
for GRCh38/unknown, liftover or reject GRCh37, reject any other confirmed build.

Why this is the strongest Tier A track to run first
---------------------------------------------------
Build detection is pure header parsing — **no external data, no network, fully
deterministic**. Unlike the GeT-RM/GIAB tracks, it needs no reference materials
to acquire, so it yields real, citable numbers the moment it runs. And because
the inputs are tiny synthetic header snippets (not human genotypes), the
fixtures are safe to commit and are unambiguously *not human subjects*.

What it measures
----------------
1. **Build-detection concordance** — detected build vs. the known build of each
   labeled fixture (reuses :func:`compare_categorical`).
2. **Gating correctness** — the action (proceed/liftover/reject) vs. the correct
   action for each (build, format, liftover-availability) case.
3. **Unsafe passes (the H-01 safety metric)** — count of coordinate-authoritative
   fixtures whose true build is a confirmed non-GRCh38 build that did **not**
   result in reject/liftover. This is the harm condition for H-01 and **must be
   0**; any nonzero value is a control failure, surfaced prominently.

This is risk-control *verification* per ISO 14971 (master plan §7, Hazard H-01).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from engine.genome_build import detect_build, plan_build_handling

from .metrics import compare_categorical

# ──────────────────────────────────────────────────────────────────────────
# Labeled fixtures — synthetic header snippets with known ground truth.
# Bytes only; no human genotype data. Each fixture states the build that is
# objectively true for it and the action the gate *should* take.
# ──────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class BuildFixture:
    id: str
    filename: str
    content: bytes
    expected_build: str           # ground-truth build of the fixture
    expected_action: str          # correct gate action given liftover_available
    liftover_available: bool = False


def _vcf(contig_len: int | None = None, reference: str | None = None) -> bytes:
    lines = ["##fileformat=VCFv4.2"]
    if reference is not None:
        lines.append(f"##reference={reference}")
    if contig_len is not None:
        lines.append(f"##contig=<ID=1,length={contig_len}>")
    lines.append("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _txt23andme(build_comment: str) -> bytes:
    return (
        f"# This data file generated by 23andMe\n"
        f"# {build_comment}\n"
        f"rsid\tchromosome\tposition\tgenotype\n"
        f"rs4477212\t1\t82154\tAA\n"
    ).encode()


FIXTURES: list[BuildFixture] = [
    # ── VCF, contig-length detection (high confidence) ────────────────────
    BuildFixture("vcf_grch38_contig", "sample.vcf",
                 _vcf(contig_len=248956422), "GRCh38", "proceed"),
    BuildFixture("vcf_grch37_contig", "sample.vcf",
                 _vcf(contig_len=249250621), "GRCh37", "reject"),
    BuildFixture("vcf_ncbi36_contig", "sample.vcf",
                 _vcf(contig_len=247249719), "NCBI36", "reject"),
    # ── VCF, ##reference text detection (medium confidence) ───────────────
    BuildFixture("vcf_grch38_refhdr", "sample.vcf",
                 _vcf(reference="GRCh38_full_analysis_set.fa"), "GRCh38", "proceed"),
    BuildFixture("vcf_grch37_refhdr", "sample.vcf",
                 _vcf(reference="file:///ref/hg19.fa"), "GRCh37", "reject"),
    # ── VCF, no build metadata → unknown → allowed (operator's responsibility)
    BuildFixture("vcf_unknown_nometa", "sample.vcf",
                 _vcf(), "unknown", "proceed"),
    # ── VCF GRCh37 WITH liftover available → must lift, not reject ─────────
    BuildFixture("vcf_grch37_liftover", "sample.vcf",
                 _vcf(contig_len=249250621), "GRCh37", "liftover",
                 liftover_available=True),
    # ── 23andMe text: build recorded but never blocks (rsID re-resolved) ──
    BuildFixture("txt_grch37_23andme", "genome.txt",
                 _txt23andme("build 37"), "GRCh37", "proceed"),
    BuildFixture("txt_grch38_23andme", "genome.txt",
                 _txt23andme("build 38"), "GRCh38", "proceed"),
    # ── CSV: build not inferable → unknown → proceed ──────────────────────
    BuildFixture("csv_unknown", "variants.csv",
                 b"chrom,pos,ref,alt\n1,82154,A,G\n", "unknown", "proceed"),
]

# Builds that are confirmed-unsafe for coordinate-authoritative files.
_NON_GRCH38_CONFIRMED = {"GRCh37", "NCBI36"}
# Actions that safely prevent silent mis-annotation.
_SAFE_ACTIONS = {"reject", "liftover"}


def _is_coordinate_authoritative(filename: str) -> bool:
    name = filename.lower()
    return name.endswith(".vcf") or name.endswith(".vcf.gz")


def run_build_validation(fixtures: list[BuildFixture] = FIXTURES) -> dict[str, Any]:
    """Run detection + gating over the fixtures and return a report dict."""
    detected: dict[tuple[str, str], str | None] = {}
    expected_build: dict[tuple[str, str], str | None] = {}

    action_results: list[dict[str, Any]] = []
    unsafe_passes: list[dict[str, Any]] = []
    n_action_correct = 0

    for fx in fixtures:
        det = detect_build(fx.content, fx.filename)
        plan = plan_build_handling(
            det, fx.filename, liftover_available=fx.liftover_available
        )
        action = plan["action"]

        key = (fx.id, "build")
        detected[key] = det["build"]
        expected_build[key] = fx.expected_build

        correct = action == fx.expected_action
        n_action_correct += int(correct)
        action_results.append({
            "id": fx.id,
            "filename": fx.filename,
            "expected_build": fx.expected_build,
            "detected_build": det["build"],
            "detection_confidence": det["confidence"],
            "detection_source": det["source"],
            "liftover_available": fx.liftover_available,
            "expected_action": fx.expected_action,
            "actual_action": action,
            "action_correct": correct,
        })

        # H-01 safety check: a coordinate file truly on a confirmed non-GRCh38
        # build that was allowed to proceed would be silently mis-annotated.
        if (
            _is_coordinate_authoritative(fx.filename)
            and fx.expected_build in _NON_GRCH38_CONFIRMED
            and action not in _SAFE_ACTIONS
        ):
            unsafe_passes.append({
                "id": fx.id,
                "expected_build": fx.expected_build,
                "actual_action": action,
            })

    detection = compare_categorical(detected, expected_build, case_sensitive=False)

    n = len(fixtures)
    return {
        "track": "genome_build_handling",
        "hazard": "H-01 (silent GRCh37/GRCh38 conflation)",
        "n_fixtures": n,
        "build_detection": detection.to_dict(),
        "gating": {
            "n_correct": n_action_correct,
            "n_total": n,
            "rate": (n_action_correct / n) if n else None,
            "results": action_results,
        },
        "safety": {
            "unsafe_passes": unsafe_passes,
            "n_unsafe_passes": len(unsafe_passes),
            # The headline pass/fail for H-01 control verification:
            "h01_control_holds": len(unsafe_passes) == 0,
        },
    }


def render_markdown(report: dict[str, Any]) -> str:
    det = report["build_detection"]
    gate = report["gating"]
    safety = report["safety"]

    def pct(x: float | None) -> str:
        return "n/a" if x is None else f"{x * 100:.1f}%"

    lines = [
        "# Tier A — Genome Build Handling Validation",
        "",
        f"Control for **{report['hazard']}**.  Fixtures: {report['n_fixtures']}",
        "",
        "## Build detection",
        f"- Concordant: {det['n_concordant']} / {det['n_compared']} "
        f"→ **{pct(det['concordance_rate'])}**",
    ]
    if det["discordances"]:
        lines.append("- Discordances:")
        for d in det["discordances"]:
            lines.append(f"  - {d['key']}: expected `{d['expected']}`, "
                         f"got `{d['observed']}`")

    lines += [
        "",
        "## Gating decisions",
        f"- Correct actions: {gate['n_correct']} / {gate['n_total']} "
        f"→ **{pct(gate['rate'])}**",
        "",
        "| Fixture | Build (exp→det) | Liftover | Action (exp→act) | OK |",
        "|---|---|---|---|---|",
    ]
    for r in gate["results"]:
        ok = "✅" if r["action_correct"] else "❌"
        lines.append(
            f"| {r['id']} | {r['expected_build']}→{r['detected_build']} "
            f"| {'yes' if r['liftover_available'] else 'no'} "
            f"| {r['expected_action']}→{r['actual_action']} | {ok} |"
        )

    verdict = "✅ HOLDS" if safety["h01_control_holds"] else "❌ FAILED"
    lines += [
        "",
        "## H-01 safety verdict",
        f"- Unsafe passes (non-GRCh38 coordinate file allowed to proceed): "
        f"**{safety['n_unsafe_passes']}**",
        f"- **H-01 control: {verdict}**",
    ]
    if safety["unsafe_passes"]:
        for u in safety["unsafe_passes"]:
            lines.append(f"  - ⚠️ {u['id']}: {u['expected_build']} → "
                         f"`{u['actual_action']}` (should reject/liftover)")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    import argparse
    import json
    from pathlib import Path

    ap = argparse.ArgumentParser(description="Tier A genome-build handling validation")
    ap.add_argument("--out-dir", default="validation/reports")
    args = ap.parse_args(argv)

    report = run_build_validation()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "tier_a_build_handling.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8")
    md = render_markdown(report)
    (out_dir / "tier_a_build_handling.md").write_text(md, encoding="utf-8")

    print(md)
    # Non-zero exit if the H-01 control fails — useful as a CI gate.
    return 0 if report["safety"]["h01_control_holds"] else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
